# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlopsazure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mlopsazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_70bfb2af3bfa434b981bcb676b87f1fb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6e602e028ecc4952b4c3990a6fce9a84 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mlopsazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_70bfb2af3bfa434b981bcb676b87f1fb }}/mlopsazure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlopsazure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c26e4d8416342c59a0a5ba3a2522097 }}
        images: 'mlopsazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_70bfb2af3bfa434b981bcb676b87f1fb }}/mlopsazure:${{ github.sha }}'